/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;

/**
 *
 * @author nitro5WIN10
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        
        setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        labelUsuarioPrivilegio = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnUsuario = new javax.swing.JButton();
        btnNotificacao = new javax.swing.JButton();
        btnConfiguracao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        textUsuarioMenuBar = new javax.swing.JMenu();
        textNotificacoesMenuBar = new javax.swing.JMenu();
        textConfiguracaoMenuBar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        btnUsuario.setText("Usuario");

        btnNotificacao.setText("Notificação");

        btnConfiguracao.setText("Configuração");

        jMenuBar1.setToolTipText("");

        textUsuarioMenuBar.setText("Usuários");
        jMenuBar1.add(textUsuarioMenuBar);

        textNotificacoesMenuBar.setText("Notificações");
        jMenuBar1.add(textNotificacoesMenuBar);

        textConfiguracaoMenuBar.setText("Configuração");
        jMenuBar1.add(textConfiguracaoMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelUsuarioPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDesktopPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuario)
                    .addComponent(btnNotificacao)
                    .addComponent(btnConfiguracao))
                .addGap(33, 33, 33)
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuarioPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLabelUsuarioPrivilegio() {
        return labelUsuarioPrivilegio;
    }

    public JMenu getTextConfiguracaoMenuBar() {
        return textConfiguracaoMenuBar;
    }

    public JMenu getTextNotificacoesMenuBar() {
        return textNotificacoesMenuBar;
    }

    public JMenu getTextUsuarioMenuBar() {
        return textUsuarioMenuBar;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public JButton getBtnUsuario() {
        return btnUsuario;
    }

    public JButton getBtnConfiguracao() {
        return btnConfiguracao;
    }

    public JButton getBtnNotificacao() {
        return btnNotificacao;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracao;
    private javax.swing.JButton btnNotificacao;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelUsuarioPrivilegio;
    private javax.swing.JMenu textConfiguracaoMenuBar;
    private javax.swing.JMenu textNotificacoesMenuBar;
    private javax.swing.JMenu textUsuarioMenuBar;
    // End of variables declaration//GEN-END:variables
}
